### ISSUE TITLE
GINO use mysql

### ISSUE THREAD

**Issue by mylot-python** [python-gino/gino#707] opened 2020-07-14 06:29 UTC
* GINO version:1
* Python version:3.8

code:
db.set_bind('mysql+aiomysql://root:123456@192.168.101.43:3306/future')

rasie exc - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mysql.aiomysql

gino not Support for mysql? If mysql is supported, How to fill in parameters?

请问gino不支持mysql吗? 如果支持, 如何填写驱动?

**Comment by wwwjfy** [comment] 2020-07-14 17:56
Duplicate of #381

**Closed by wwwjfy** 2020-07-14 17:56 UTC
Labels: duplicate
